### ISSUE TITLE
[FEATURE] Column level metrics tracking

### ISSUE THREAD

**Issue by mateuszklimek** [re-data/re-data#119]
**Tell us about the problem you're trying to solve**
Sometimes you only want to compute base metrics for some columns of a given table.

**Describe the solution you’d like**

```
  re_data:monitored:
    - tables:
        - name: sample_table
          time_filter: creation_time
          columns: 
            - col1
            - col2
            - col3
```

This would make re_data only run metrics on specified columns
