### ISSUE TITLE
[FEATURE] Overwrite metrics

### ISSUE THREAD

**Issue by ludogayet** [re-data/re-data#286]
**Tell us about the problem you're trying to solve**
Base on the slack [discussion](https://re-data.slack.com/archives/C0295HAUJHG/p1652284893650399)
What are you trying to do?

I'm trying to use multiple times the same metrics match_regex without having to define custom metrics :
```
metrics:
            column:
              rating:
                - match_regex:
                    regex: (new_user)
                - match_regex:
                    regex: (engaged)
                - match_regex:
                    regex: (disengaged)
......
```

**Describe the solution you’d like**

A clear and concise description of what you want to see happen.
Being able to add a `name` that is being appended to the metric's name. So that we avoid the Error message : `Column name rating___match_regex is ambiguous at [524:141]`

```
metrics:
            column:
              rating:
                - match_regex:
                    name: new_user
                    regex: (new_user)
                - match_regex:
                    name: engaged
                    regex: (engaged)
                - match_regex:
                    name: disengaged
                    regex: (disengaged)
......
```

**Describe the alternative you’ve considered or used**

The alternatives is custom metrics but it seems a bit annoying to define X metrics everytime.
