### ISSUE TITLE
[FEATURE] More flexible metrics

### ISSUE THREAD

**Issue by mateuszklimek** [re-data/re-data#312]
**Tell us about the problem you're trying to solve**

Currently, the way re_data lets you define metrics is not super flexible and a lot of repetition may be needed in quite some cases.
Also, it's not very intuitive that the `re_data_metrics` config corresponds to just **additional** metrics re_data computes for the model and even when you define it `re_data:metrics_base` would still be used in the specific model.

**Describe the solution you’d like**

The proposal would be to introduce 2 new config variables re_data:metrics_groups & re_data:metrics_default_groups
``` 
re_data:metrics_groups:
    - table_metrics:
        table:
          - row_count
          - freshness

    - column_metrics:
        column:
          numeric:
            - min
            - max
            - avg
            - stddev
            - variance
            - nulls_count
            - nulls_percent
          text:
            - min_length
            - max_length
            - avg_length
            - nulls_count
            - missing_count
            - nulls_percent
            - missing_percent

 re_data:metrics_default_groups:
    - table_metrics
    - column_metrics
```
*The above would actually be defaults in re_data dbt_project.yml*

Apart from that `re_data_metrics` config would now accept the list of metrics:
```
re_data_metrics:
  - table_metrics
  - column_metrics
  - my_custom_group
  - table:
      - something
    column:
      numeric:
        - min
      text:
        - min_lenth
```

*For backward compatibility, it can also accept just a dictionary with table/column keys as now.*

`re_data:metrics_base` from the current version would be removed, if this config was overwritten quite easy migration is to 
create a single group in `re_data:metrics_groups` with values previously there and make it an only default group

Apart from more flexibility, this implementation allows easily making mode/set of models to compute only table/column metrics.
