### ISSUE TITLE
[BUG] Anomaly detected on avg numeric column when the value was exactly the same for the whole month

### ISSUE THREAD

**Issue by FrankTub** [re-data/re-data#319]
**Describe the bug**
I'm trying to incorporate `re_data` into my dbt project and ran some tests on several days. Now I run it again and check the output again I'm really confused. On a lot of columns an anomaly is detected, while the difference between previous runs was very very small, or there was no difference at all. The behavior I describe here happens for a lot of columns. See image below for an example.

![image](https://user-images.githubusercontent.com/19519819/177117613-df517e17-3a86-4064-8632-481ef6a705fd.png)

When you look at the test history it looks very weird that this particular step is marked as an anomaly. If you hover over the values that are displayed are both exactly `82,311.48`.

![image](https://user-images.githubusercontent.com/19519819/177118125-363c9d51-070b-4101-8e0d-78bfe4008993.png)

Running this with `dbt 1.1.0`  and `re_data 0.9.2` and `postgres 13`.

generated the overview as following.

```bash
re_data overview generate --start-date 2022-06-01 --end-date 2022-06-29
re_data overview serve 
```

Using the following configuration.

```yml
vars:
  # (optional) if not passed, stats for last day will be computed
  re_data:time_window_start: '{{ (run_started_at - modules.datetime.timedelta(1)).strftime("%Y-%m-%d 00:00:00") }}'
  re_data:time_window_end: '{{ run_started_at.strftime("%Y-%m-%d 00:00:00") }}'

  # (optional) override standard metrics computed for all your tables
  re_data:metrics_base:
    table:
      - row_count

    column:
      numeric:
        - min
        - max
        - avg
        - nulls_count

      text:
        - min_length
        - max_length
        - avg_length
        - nulls_count

  # (optional) tells how much hisory you want to consider when looking for anomalies
  re_data:anomaly_detection_look_back_days: 30

  # (optional) configuring storing tests history
  re_data:save_test_history: true

  # (optional) querying db for failing rows
  re_data:query_test_failures: true

  # (optional) configuring storing table samples
  re_data:store_table_samples: false

  re_data:anomaly_detector:
      name: modified_z_score
      threshold: 3
```

**Expected behavior**
No anomaly detection when there is no anomaly.

**To Reproduce**

Not really sure when it does or doesn't happen. But these are the steps I followed.

```bash
dbt deps
pip install re_data
dbt run
re_data run --start-date 2022-06-01 --end-date 2022-06-16 --interval days:1
```

**Screenshots**
N/A

**Logs and additional context**
Based on conversation on slack also ran the following query. It looks like some weird rounding things are going on when detected anomalies.

```sql
select table_name, column_name , metric, time_window_end, z_score_value , modified_z_score_value, "last_value" , last_avg , last_stddev, last_mean_absolute_deviation, last_median, last_median_absolute_deviation, last_iqr, last_first_quartile, last_third_quartile  
from   re.re_data_z_score
where 1=1
and table_name = '"staging"."transformations"."lease_contracts"'
and column_name = 'current_payout'
and metric = 'global__avg'
and id <> 'c7f4c7d4118f3d4393d078745e53fe16'
order by time_window_end desc
```

The output is as follow:

![image](https://user-images.githubusercontent.com/19519819/177119763-7ddd1f06-68ff-4122-af47-a1a5ec0556c7.png)
