### ISSUE TITLE
[FEATURE] Choose (or disable) anomaly_detector per metric group

### ISSUE THREAD

**Issue by mateuszklimek** [re-data/re-data#337]
**Choosing anomaly detector per metrics group with optionally disabling anomaly detection altogether**

```
re_data:metrics_groups:
  group:
    anomaly_detector:
      name: none
  
    table:
      - row_count
      - freshness
    column:
      - ...

```
