### ISSUE TITLE
[FEATURE] Allow configuring anomaly detection per metric groups

### ISSUE THREAD

**Issue by mateuszklimek** [re-data/re-data#338]
**Tell us about the problem you're trying to solve**

What are you trying to do?

```
re_data:metrics_groups:
  group:
    anomaly_detector:
      name: none
  
    table:
      - row_count
      - freshness
    column:
      - ...

```
