### ISSUE TITLE
[FEATURE] Allow to target tags/column names in metric groups

### ISSUE THREAD

**Issue by mateuszklimek** [re-data/re-data#339]
**Tell us about the problem you're trying to solve**

Sometimes users would like to compute different metrics for different columns

**Describe the solution you’d like**

```
re_data:metrics_groups:
   metrics_for_columns_with_tag1:
    column:
      tag:tag1:
        - min
        - max
        - avg

   metrics_for_columns_with_tag2:
     column:
       tag:tag_name2:
        - avg
        - sum
```
