### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by FrankTub** [re-data/re-data#363]
**Describe the bug**

We use re_data to alert users through email notifications of failed tests. In our setup it is possible that the same owner is responsible for different models. If more than one model fails that is owned by the same owner, this owner will receive __the same__ email the number of times the different model has failed tests. In a single mail all the different models are mentioned with the number of failed tests on them. But this mail is thus repeated several times.

**Expected behavior**

We would expect either a single mail for all the different models per owner. OR a mail per model that has failed per owner.

**To Reproduce**

Create model A & B something like.

```sql
select 1 as id
```

Create for both models a `schema.yml`:

```yml
version: 2

models:
  - name: A|B
    description: Test table
    config:
      re_data_owners:
        - owner
    tests:
      - dbt_utils.expression_is_true:
          name: "assertion_A"
          expression: "id = 0"
```

Set the owner in your `dbt_project.yml`:

```yml
  re_data:owners_config:
    owner:
      - type: email
        identifier: <your-mail>
        name: <Your Name>
```

Configure your email setup in `~/.re_data/re_data.yml`:

```
notifications:
  email:
    mail_from: <your-mail>
    smtp_host: <your-host>
    smtp_port: <your-port>
    smtp_user: <your-user>
    smtp_password: <your-password>
    use_ssl: false
    use_tls: true
```

Then run the following bash commands in your dbt project.

```bash
dbt run --exclude re_data
dbt test
re_data overview generate
re_data notify email --select test
```

**Screenshots**

![image](https://user-images.githubusercontent.com/19519819/194244279-626993b7-1636-4d78-ae96-fa8ceaf4cfe7.png)

**Logs and additional context**

https://re-data.slack.com/files/U03KE7WF3EX/F04533QDQUE/monitored.json?origin_team=T01FUT83076&origin_channel=D0459D96V51

https://re-data.slack.com/files/U03KE7WF3EX/F0456P4LTBP/alerts.json?origin_team=T01FUT83076&origin_channel=D0459D96V51
