### ISSUE TITLE
[BUG] test names are not display correctly

### ISSUE THREAD

**Issue by bachng2017** [re-data/re-data#394]
**Describe the bug**
Test names are not displayed correctly in the UI, only popup show the name

**Expected behavior**
Test names are displayed correctly

**To Reproduce**
Run some test with dbt_re_data 0.10.7. Sometimes the display is fine, sometime it is not. _And we do not know the condition to reproduce it yet_
```
...
  - name: dwh__m365schedule
    description: O365 scheduler (~12:00 JST everyday)
    database: boar
    tables:
      - name: schedule
        description: 0365 schedular
        config:
          re_data_monitored: true
          re_data_anomaly_detector: {'name': 'z_score', 'threshold': 3}
          re_data_time_filter: date_add('day',2,parse_datetime(cast(dt as varchar),'yyyyMMdd'))
        tests:
          - re_data.assert_greater:
              metric: row_count
              value: 0
              ...
```              

**Screenshots**
<img width="1602" alt="スクリーンショット 2023-03-25 22 12 02" src="https://user-images.githubusercontent.com/31262506/227719309-e239d106-e807-43bc-bf14-b9e588033860.png">

**Logs and additional context**
test results  are stored correctly
```
> select * from re_data_test_history;
           table_name            | column_name |                                                  test_name                                                  | status |   execution_time   | message | failures_count | failures_json |      >
---------------------------------+-------------+-------------------------------------------------------------------------------------------------------------+--------+--------------------+---------+----------------+---------------+------>
 boar.dwh__m365schedule.schedule | NULL        | re_data_source_assert_greater_dwh__m365schedule_schedule_time_window_start_date_2023_03_01___min__100000000 | Pass   |  1.561762809753418 | NULL    |            0.0 |               | boar.>
 boar.dwh__m365schedule.schedule | NULL        | re_data_source_assert_greater_dwh__m365schedule_schedule_time_window_start_date_2023_03_01___min__100000000 | Pass   | 1.4910774230957031 | NULL    |            0.0 |               | boar.>
 boar.dwh__m365schedule.schedule | NULL        | re_data_source_assert_greater_dwh__m365schedule_schedule_time_window_start_date_2023_03_01___min__0         | Pass   |  2.266712188720703 | NULL    |            0.0 |               | boar.>
(3 rows)
```
