### ISSUE TITLE
[FEATURE] Only create anomaly only on increase or decrease

### ISSUE THREAD

**Issue by davidzajac1** [re-data/re-data#410]
**Tell us about the problem you're trying to solve**

Often times we only care about anomalies for a sudden decrease or increase but not both. For example a big increase in the number of paying customers is positive and isn't an issue for the business but a big sudden decrease is a huge immediate problem.

**Describe the solution you’d like**

The ability to specify if a metric should have an anomaly only for a decrease or increase. Right now it will always creates an anomaly for both. It would be configured like this in the `dbt_project.yml` file:

```yaml
models:
  toy_shop:
    revenue:
      +re_data_anomaly_detector:
        name: modified_z_score
        threshold: 3
        direction: up | down | both
```

**Describe the alternative you’ve considered or used**

Just dealing with the extra anomalies.
