### ISSUE TITLE
[FEATURE] different granularities for different metrics

### ISSUE THREAD

**Issue by suelai** [re-data/re-data#414]
**Tell us about the problem you're trying to solve**

A day granularity works well for most of the metrics and the immediate spikes but some of the metrics shift slowly and `re_data` won't catch that. Or sometimes the values are very small on the day granularity, but if we aggregate on the week/month level, we can see the change better. It will be helpful to have a time_granularity parameter to define this.

**Describe the solution you’d like**
Something like this, where the sum of the amount will be aggregated on the monthly level and then calculate the metrics
```
models:
  - name: pending_orders
    config:
      re_data_monitored: true
      re_data_time_filter: created_at
      re_data_columns:
        - amount
        - status
      re_data_metrics_groups:
        - table_metrics
      re_data_metrics:
        column:
          amount:
            - sum:
               time_granularity: month
      re_data_anomaly_detector:
        name: modified_z_score
        threshold: 3
```

**Describe the alternative you’ve considered or used**
