### ISSUE TITLE
[BUG] Custom test name is not displayed in test list on overiew site

### ISSUE THREAD

**Issue by mbyrne00** [re-data/re-data#423]
**Describe the bug**
When I have `data_tests` entries that are using the [custom test name](https://docs.getdbt.com/reference/resource-properties/data-tests#custom-data-test-name) configuration, the `Tests` list to the right of the model does not show that custom name. When I click to see detail, the dropdown under `Test Details` shows the correct name (e.g. `no_assets` and `all_assets_bad_data` in my example).

Expect to see the same custom name in the original list, to allow the user to easily differentiate between my tests. It is currently showing the raw test name as below.

![image](https://github.com/re-data/re-data/assets/5687982/2c053481-f5e2-4764-9f25-9b3558f9fd36)

In this example  have a macro called `is_empty` that is merely a `SELECT` on a table I expect no rows in (this is used for reconciliation views) and it supports a parameter `where`. This is sample YAML config.

```yaml
version: 2

models:
  - name: my_model_containing_bad_data
    data_tests:
      - is_empty:
          name: no_assets
          where: "asset_count = 0"
      - is_empty:
          name: all_assets_bad_data
          where: "asset_count > 0"
```

**Expected behavior**
Consistently show the custom test name across all screens and widgets.

**To Reproduce**
Create two tests using the same test macro and with custom names. Custom names will not show on side-list for model view, but will show when you click to test details.

**Screenshots**
![image](https://github.com/re-data/re-data/assets/5687982/2c053481-f5e2-4764-9f25-9b3558f9fd36)

**Logs and additional context**
If application, any other context, logs etc.here
